### ISSUE TITLE
Data-checking fiche RECIST

### ISSUE THREAD

**Issue by DanChaltiel** [Oncostat/grstat#25]
TL = target lesion, NTL = non-target lesion, NL = new lesion

## Checks Data

- [x] `RCTDIAM` à baseline > 10 pour tumeurs, 15 pour ganglions
Indépendant de la méthode (XRay déprécié, caliper que en dermato, IRM == CTScan)
- [x] Manquants sur diamètre & site : soit aucun, soit les deux
- [x] Pas plus de 5 target lesions
- [x] Pas plus de 2 target lesions par "organe"
- [x] target lesions toujours les même pendant le suivi
- [x] `RCTLMOD` unique par patient
- [x] Recalcul de `RCTLSUM`, `RCTLBL`, `RCTLMIN`...
- [x] checker la cohérence entre `nontarget_yn` et `nontarget_resp`
- [x] Lésion osseuse jamais TL (peut être NTL ou NL)
- [x] Si progression exclusivement sur NTL, query pour confirmer
- [ ] Si progression exclusivement sur NL osseuse, query pour confirmer que pas "healing" ou "flare"
- [ ] Si diamètre=0, diamètre ultérieur=0 (Si une lésion disparait, réémergence = nouvelle lésion)

NB: Pas de test possible pour la TL-complete response au niveau des ganglions NTL, on doit faire confiance

## Checks Calcul

- [x] **TL-CR** : tous les` RCTDIAM = 0` si non-ganglion, `RCTDIAM < 10` si ganglion
Pas 100% déterministe dans l'autre sens : les ganglions NTL doivent être <10mm et on n'a pas (encore) l'info
- [x] **TL-PR** : `RCTSUM_t` / `RCTSUM_baseline` < 0.7
Cas limite :
Tumeur 11 + gg 15 → 18.2 pour PR
Tumeur 11 + gg 1 → PR
- [x] **TL-PD** : `RCTSUM t/nadir > 1.2` AND `t-nadir > 5mm`
Cas limite :
tumeur 7 → 11 +50% mais <5 donc pas PD, juste SD
- [x] **TL-SD** : tout le reste

En l'état, difficile de vérifier les NTL, et donc le tableau n'est pas très utilisable :
- [x] **NTL-CR** : `RCNTLPRE` peut valoir "présent" mais être <10mm dans les ganglions
- [x] **NTL-PD** : On n'a pas l'info par lésion pour faire un check. La décision de considérer une NTL comme progressive est assez subjective.
- [x] **NTL-nonCRnonPD** : par construction, non checkable
- [ ] Si tout `RCNTLPRE` = "absent", on peut imaginer que c'est CR ?

## TODO misc

- [ ] `output_file`: `dir_create()`
- [ ] passer check sur RCTLMOD en warning plutôt que erreur

## Changer le CRF standard : 

- [x] Ajouter PET dans RCNEWMOD (PET Scan = taille non évaluable mais possible nouvelle lésion)
- [x] Changer le wording de RCTDIAM : "longest diameter for non-nodes, short-axis diameter for nodes"
- [ ] Ajouter un label ou une variable à RCNTLPRE : "si ganglion, <10mm" ?
- [x] Rendre RCNTLLOC toujours saisissable
- [x] Ajouter RCNTLRESP pour chaque NTL séparément. 
Permettrait de savoir sur quel type de tumeur le traitement est le plus efficace

<details><summary>Ressources </summary>
<p>

### RECIST 1.1 Documentation

- Princeps article: Eisenhauer 2008 https://ctep.cancer.gov/protocoldevelopment/docs/recist_guideline.pdf 
- PDF from CEPD cohort (Fr): http://www.cepd.fr/CUSTOM/RECIST_1.1.pdf
- Powerpoint from Pneumology Society (Fr): https://splf.fr/wp-content/uploads/2017/10/Lederlin-M_RECIST-Un-petit-cours-pratique.pdf

### RECIST Calculators:
- https://www.radrap.ch/calculateurs
- https://radcalculators.org/recist-1-1-calculator/

### Other resources:
- calcul SAS du recist 1.1 target lesions sur données ADAM (PDF): [lien](https://www.lexjansen.com/sesug/2019/SESUG2019_Paper-281_Final_PDF.pdf)
- https://www.lexjansen.com/pharmasug-cn/2023/SA/Pharmasug-China-2023-SA142.pdf
- https://cran.r-project.org/web/packages/admiralonco/vignettes/adtr.html
- https://github.com/luoj2/mlRECIST

### Off-topic
* Compute the Best Overall Response: https://www.bioinfo-scrounger.com/archives/bor_recist/. See also https://github.com/kaigu1990/stabiot

</p>
</details>
